# ZMK Build Configuration for Corne with Dongle Setup

include:
  # Dongle - Central device (connects to computer via USB)
  - board: nice_nan_v2
    shield: corne_dongle
    artifact-name: corne_dongle-nice_nano

  # Left half - Peripheral (connects to dongle via BLE)
  - board: nice_nano_v2
    shield: corne_left
    artifact-name: corne_left-nice_nano

  # Right half - Peripheral (connects to dongle via BLE)
  - board: nice_nano_v2
    shield: corne_right
    artifact-name: corne_right-nice_nano

  # Settings reset firmware - flash this first on all devices to clear pairing
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset-nice_nano
