# ZMK Build Configuration for Corne with Dongle Setup

include:
  # Dongle - Central device with ZMK Studio support
  - board: nice_nano_v2
    shield: corne_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_dongle-nice_nano

  # Left half - Peripheral
  - board: nice_nano_v2
    shield: corne_peripheral_left
    artifact-name: corne_left-nice_nano

  # Right half - Peripheral
  - board: nice_nano_v2
    shield: corne_peripheral_right
    artifact-name: corne_right-nice_nano

  # Settings reset firmware
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset-nice_nano
